### ISSUE TITLE
Загружать параметры игры из JSON

### ISSUE THREAD

**Issue by Silmarill** [Silmarill/mediators-voice-nerdy-phantasm#16]
MainMenu.cs

Все что грузится в PlayerPrefs должно получаться из JSON.

http://wiki.unity3d.com/index.php/SimpleJSON  вот эта библиотека

Не использовать встроенную. (она хуже)

**Comment by Belobopka** [comment]
Реализация типо такой? https://i.imgur.com/VXtGNNQ.png

**Comment by Silmarill** [comment]
Нет. Посмотри раздел **Usage** в http://wiki.unity3d.com/index.php/SimpleJSON 
Есть еще такой пост с примером
https://forum.unity.com/threads/using-simplejson.242044/#post-1602388

Единственное что, для ссылки на текстовый файл надо вот так:

```
using SimpleJSON;
....
private TextAsset jsonFile;
//В папке Assets\Resources должен лежать файл settings.json
private readonly string FILE_NAME = "settings"; 
....
jsonFile = (TextAsset)Resources.Load(FILE_NAME);
string theJsonText = file.text;
N = JSON.Parse(theJsonText);
var firstPlayer = N[0];
//"test"
var username = firstPlayer["Player"]["username"].Value;
// "10"
var score = firsePlayer["Score"]["score"].Value;
```

Но в разделе Usage все ж лучше.
