### ISSUE TITLE
Сделать нормальную паузу.

### ISSUE THREAD

**Issue by Silmarill** [Silmarill/mediators-voice-nerdy-phantasm#22]
Использовать Observer
[Observer.zip](https://github.com/Silmarill/mediators-voice-nerdy-phantasm/files/1326828/Observer.zip)

**Comment by Belobopka** [comment]
Вопрос, вот есть два класса https://github.com/Silmarill/mediators-voice-nerdy-phantasm/blob/master/Assets/Scripts/EnemyHealthManager.cs - смотрит за хп и уничтожает гейм обжект,по логике тут должны бы и ремувится листенеры, но листенеры я расположил тут https://github.com/Silmarill/mediators-voice-nerdy-phantasm/blob/master/Assets/Scripts/EnemyPatrol.cs - потому, что тут можно деактивировать обновление объекта и т.д. . 
Может стоит объеденять такие классы в один?

**Comment by Belobopka** [comment]
Сделал ветку, вот мои классы https://github.com/Silmarill/mediators-voice-nerdy-phantasm/blob/ISS22/Assets/Scripts/EnemyPatrol.cs - тут листенер.
https://github.com/Silmarill/mediators-voice-nerdy-phantasm/blob/ISS22/Assets/Scripts/EnemyHealthManager.cs - тут дестроится геймобжект 
Messenger.RemoveListener("GameIsResumed", onResume); 
Тут забыл поменять.Должно быть 
Messenger.RemoveListener<bool>("PauseStatus", pauseStatus);

**Comment by Belobopka** [comment]
Работает для объектов, но с буллетами проблема, в классах https://github.com/Silmarill/mediators-voice-nerdy-phantasm/blob/ISS22/Assets/Scripts/EnemyProjectileController.cs и https://github.com/Silmarill/mediators-voice-nerdy-phantasm/blob/ISS22/Assets/Scripts/ProjectileController.cs
Используется метод onDisable, speed = speedOnStart;

**Comment by Belobopka** [comment]
Сделал логику в самих буллетах,у них нет апдейта,поэтому сделал немножк по другому.Побегал все работает.

**Comment by Silmarill** [comment]
Выполнено.
