### ISSUE TITLE
Сделать нормальные Хазарды

### ISSUE THREAD

**Issue by Silmarill** [Silmarill/mediators-voice-nerdy-phantasm#29]
Класс хазард с переопределямой логикой.

**Comment by Belobopka** [comment]
Задача в создании абстрактного класса  хазард, от которого наследуются  тайлы, представляющие опасность для игрока?

**Comment by Silmarill** [comment]
Сделать абстрактный класс Hazard.cs с основной логикой поведения "опасного объекта". Повесить его на объект и сделать префаб. "Тайлы" не могут наследоваться. Они будут получаться путем замены спрайта в SpriteRenderer и замены контроллера в компоненте Animator. Скрипт нужен на случай прям замены логики.

**Comment by Silmarill** [comment]
Отменен
