### ISSUE TITLE
Враг стреляет в мертвого ГГ уменьшая хп.

### ISSUE THREAD

**Issue by Silmarill** [Silmarill/mediators-voice-nerdy-phantasm#37]

**Comment by Belobopka** [comment]
Враги используют скрипт HurtPlayerOnContact , но я не вижу проверки по хп

**Comment by Silmarill** [comment]
Не не. Там типа прожектайл наносит урон даже если игрок мертвый. Смотри скрипт вражеского прожектайла

**Comment by Belobopka** [comment]
Я глянул RespawnPlayerCoorutine() метод в levelmanager, там нету адекватного выключения игрока,чтобы ему не наносился урон, для теста включел делей респ тайма 10 сек и проверил,так и есть, во время респавн тайма враги наносят урон.

**Comment by Belobopka** [comment]
И по ощущениям это не только на прожектайлы, так же и летающий враг убивается об игрока во время респавн тайма.

**Comment by Silmarill** [comment]
Очень элегантно решено.
