### ISSUE TITLE
Управление под Andoid

### ISSUE THREAD

**Issue by Silmarill** [Silmarill/mediators-voice-nerdy-phantasm#5]
Джойстик вместо стрелок
Поправить логику на:
- Лестницы
- Окончание левела

**Comment by Silmarill** [comment]
Что-то в этом роде http://www.devination.com/2015/09/unity-touch-joysticks-tutorial-touch.html

**Comment by Belobopka** [comment]
Попробую.

**Comment by Silmarill** [comment]
Сделано
