### ISSUE TITLE
Появлющиеся из пола шипы

### ISSUE THREAD

**Issue by Silmarill** [Silmarill/mediators-voice-nerdy-phantasm#6]
Hazarad, появляющийся из пола.

**Comment by Belobopka** [comment]
Беру. Буду думать

**Comment by Belobopka** [comment]
https://github.com/Silmarill/mediators-voice-nerdy-phantasm/tree/ISS6 
Вроде скрипт подойдет для любых хазардов по сути. Возможность задавать свои координаты сдвига позволяет сделать и совершенно другие виды ловушек.
